import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.imagewrap}>
          {/*<Image className={styles.myimg} src="/homeimg.jpg" alt="homeimg" width={207} height={138} />*/}
          <img className={styles.myimg} src="/homeimg.jpg" alt="Homeimg" width={207} height={138} />
        </div>
        <div className={`${geistSans.variable} ${geistMono.variable}`}>
          <h1 className={styles.title}>
            <span className={styles.h1}>&lt;Hunting Coder/&gt;</span>
          </h1>

          <p className={styles.description}>
            A blog for hunting coders by a hunting coders. Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit corporis aspernatur, voluptatem sed dolor asperiores nihil ut eveniet non amet quo culpa. Voluptates soluta facilis vitae voluptatem dignissimos?
          </p>

          <div className={styles.blogs}>
            <h2 className={styles.titleh2} >Latest Blogs</h2>
            <div className={styles.blogitem}>
              <h3 className={styles.titleh3}>How to learn Javascript 2025?</h3>
              <p className={styles.p}>Javascript is the language used to design logic for the web</p>
            </div>
            <div className={styles.btnwrap}>
              <button className={styles.btn}>Read More</button>
            </div>

            <div className={styles.blogitem}>
              <h3 className={styles.titleh3}>How to learn Javascript 2025?</h3>
              <p className={styles.p}>Javascript is the language used to design logic for the web</p>
            </div>
           <div className={styles.btnwrap}>
              <button className={styles.btn}>Read More</button>
            </div>

            <div className={styles.blogitem}>
              <h3 className={styles.titleh3}>How to learn Javascript 2025?</h3>
              <p className={styles.p}>Javascript is the language used to design logic for the web</p>
            </div>
            <div className={styles.btnwrap}>
              <button className={styles.btn}>Read More</button>
            </div>

          </div>
        </div>
      </main>
    </div>
  );
}
